// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parbad.Data.Context;

namespace Parbad.Data.Migrations
{
    [DbContext(typeof(ParbadDataContext))]
    partial class ParbadDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parbad.Data.Domain.Payments.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PaymentID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("TrackingNumber");

                    b.Property<string>("Token");

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("GatewayName");

                    b.Property<bool>("IsCompleted");

                    b.Property<bool>("IsPaid");

                    b.Property<string>("TransactionCode");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id", "TrackingNumber", "Token");

                    b.ToTable("TbPayment","parbad");
                });

            modelBuilder.Entity("Parbad.Data.Domain.Transactions.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalData");

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsSucceed");

                    b.Property<string>("Message");

                    b.Property<long>("PaymentId");

                    b.Property<string>("PaymentToken")
                        .IsRequired();

                    b.Property<long>("PaymentTrackingNumber");

                    b.Property<byte>("Type");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id")
                        .HasName("TransactionID");

                    b.HasIndex("PaymentId", "PaymentTrackingNumber", "PaymentToken");

                    b.ToTable("TbTransaction","parbad");
                });

            modelBuilder.Entity("Parbad.Data.Domain.Transactions.Transaction", b =>
                {
                    b.HasOne("Parbad.Data.Domain.Payments.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId", "PaymentTrackingNumber", "PaymentToken")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
