// Copyright (c) Parbad. All rights reserved.
// Licensed under the GNU GENERAL PUBLIC License, Version 3.0. See License.txt in the project root for license information.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parbad.Gateway.Melli.ResultTranslator {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MelliRequestResponseCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MelliRequestResponseCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parbad.Providers.Melli.ResultTranslator.MelliRequestResponseCodes", typeof(MelliRequestResponseCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش موفق.
        /// </summary>
        internal static string Code0 {
            get {
                return ResourceManager.GetString("Code0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب پارامترهای ارسالی اشتباه می باشد، لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string Code1000 {
            get {
                return ResourceManager.GetString("Code1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند،پارامترهای پرداخت اشتباه می باشد.
        /// </summary>
        internal static string Code1001 {
            get {
                return ResourceManager.GetString("Code1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سیستم- تراکنش ناموفق.
        /// </summary>
        internal static string Code1002 {
            get {
                return ResourceManager.GetString("Code1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP پذيرنده اشتباه است.لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string Code1003 {
            get {
                return ResourceManager.GetString("Code1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند،شماره پذيرنده اشتباه است.
        /// </summary>
        internal static string Code1004 {
            get {
                return ResourceManager.GetString("Code1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای دسترسی:لطفا بعدا تلاش فرمايید.
        /// </summary>
        internal static string Code1005 {
            get {
                return ResourceManager.GetString("Code1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در سیستم.
        /// </summary>
        internal static string Code1006 {
            get {
                return ResourceManager.GetString("Code1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تکراری- شماره سفارش تکراری می باشد.
        /// </summary>
        internal static string Code1011 {
            get {
                return ResourceManager.GetString("Code1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پذيرنده صحیح نیست،يکی از موارد تاريخ،زمان يا کلید تراکنش اشتباه است.لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string Code1012 {
            get {
                return ResourceManager.GetString("Code1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ خطای نامشخص از سمت مرکز.
        /// </summary>
        internal static string Code1015 {
            get {
                return ResourceManager.GetString("Code1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی شما جهت پرداخت از حد مجاز تعريف شده برای اين پذيرنده بیشتر است.
        /// </summary>
        internal static string Code1017 {
            get {
                return ResourceManager.GetString("Code1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکال در تاريخ و زمان سیستم. لطفا تاريخ و زمان سرور خود را با بانک هماهنگ نمايید.
        /// </summary>
        internal static string Code1018 {
            get {
                return ResourceManager.GetString("Code1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان پرداخت از طريق سیستم شتاب برای اين پذيرنده امکان پذير نیست.
        /// </summary>
        internal static string Code1019 {
            get {
                return ResourceManager.GetString("Code1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذيرنده غیرفعال شده است.لطفا جهت فعال سازی با بانک تماس بگیريد.
        /// </summary>
        internal static string Code1020 {
            get {
                return ResourceManager.GetString("Code1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس بازگشت پذيرنده نامعتبر است.
        /// </summary>
        internal static string Code1023 {
            get {
                return ResourceManager.GetString("Code1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهر زمانی پذيرنده نامعتبر است.
        /// </summary>
        internal static string Code1024 {
            get {
                return ResourceManager.GetString("Code1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امضا تراکنش نامعتبر است.
        /// </summary>
        internal static string Code1025 {
            get {
                return ResourceManager.GetString("Code1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفارش تراکنش نامعتبر است.
        /// </summary>
        internal static string Code1026 {
            get {
                return ResourceManager.GetString("Code1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پذيرنده نامعتبر است.
        /// </summary>
        internal static string Code1027 {
            get {
                return ResourceManager.GetString("Code1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ترمینال پذيرنده نامعتبر است.
        /// </summary>
        internal static string Code1028 {
            get {
                return ResourceManager.GetString("Code1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس IP پرداخت در محدوده آدرس های معتبر اعلام شده توسط پذيرنده
        ///نیست .لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string Code1029 {
            get {
                return ResourceManager.GetString("Code1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس Domain پرداخت در محدوده آدرس های معتبر اعلام شده توسط
        ///پذيرنده نیست .لطفا مسئول فنی پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string Code1030 {
            get {
                return ResourceManager.GetString("Code1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهلت زمانی شما جهت پرداخت به پايان رسیده است.لطفا مجددا سعی
        ///بفرمايید.
        /// </summary>
        internal static string Code1031 {
            get {
                return ResourceManager.GetString("Code1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت با اين کارت . برای پذيرنده مورد نظر شما امکان پذير نیست.لطفا از
        ///کارتهای مجاز که توسط پذيرنده معرفی شده است . استفاده نمايید.
        /// </summary>
        internal static string Code1032 {
            get {
                return ResourceManager.GetString("Code1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به علت مشکل در سايت پذيرنده. پرداخت برای اين پذيرنده غیرفعال شده
        ///است.لطفا مسوول فنی سايت پذيرنده با بانک تماس حاصل فرمايند.
        /// </summary>
        internal static string Code1033 {
            get {
                return ResourceManager.GetString("Code1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات اضافی ارسال نشده يا دارای اشکال است.
        /// </summary>
        internal static string Code1036 {
            get {
                return ResourceManager.GetString("Code1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پذيرنده يا شماره ترمینال پذيرنده صحیح نمیباشد.
        /// </summary>
        internal static string Code1037 {
            get {
                return ResourceManager.GetString("Code1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا: درخواست معتبر، از سمت پذيرنده صورت نگرفته است لطفا اطلاعات
        ///پذيرنده خود را چک کنید.
        /// </summary>
        internal static string Code1053 {
            get {
                return ResourceManager.GetString("Code1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار غیرمجاز در ورود اطلاعات.
        /// </summary>
        internal static string Code1055 {
            get {
                return ResourceManager.GetString("Code1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم موقتا قطع میباشد.لطفا بعدا تلاش فرمايید..
        /// </summary>
        internal static string Code1056 {
            get {
                return ResourceManager.GetString("Code1056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرويس پرداخت اينترنتی خارج از سرويس می باشد.لطفا بعدا سعی
        ///بفرمايید..
        /// </summary>
        internal static string Code1058 {
            get {
                return ResourceManager.GetString("Code1058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشکال در تولید کد يکتا. لطفا مرورگر خود را بسته و با اجرای مجدد مرورگر
        ///« عملیات پرداخت را انجام دهید )احتمال استفاده از دکمه Back »
        ///مرورگر(.
        /// </summary>
        internal static string Code1061 {
            get {
                return ResourceManager.GetString("Code1061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مجددا سعی بفرمايید.
        /// </summary>
        internal static string Code1064 {
            get {
                return ResourceManager.GetString("Code1064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط ناموفق .لطفا چند لحظه ديگر مجددا سعی کنید.
        /// </summary>
        internal static string Code1065 {
            get {
                return ResourceManager.GetString("Code1065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم سرويس دهی پرداخت موقتا غیر فعال شده است.
        /// </summary>
        internal static string Code1066 {
            get {
                return ResourceManager.GetString("Code1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با عرض پوزش به علت بروزرسانی . سیستم موقتا قطع میباشد..
        /// </summary>
        internal static string Code1068 {
            get {
                return ResourceManager.GetString("Code1068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پردازش پارامترهای اختیاری پذيرنده.
        /// </summary>
        internal static string Code1072 {
            get {
                return ResourceManager.GetString("Code1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش نامعتبر است.
        /// </summary>
        internal static string Code1101 {
            get {
                return ResourceManager.GetString("Code1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن ارسالی نامعتبر است.
        /// </summary>
        internal static string Code1103 {
            get {
                return ResourceManager.GetString("Code1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تسهیم صحیح نیست.
        /// </summary>
        internal static string Code1104 {
            get {
                return ResourceManager.GetString("Code1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Merchant. پذيرنده کارت فعال نیست لطفا با بخش امور پذيرندگان، تماس حاصل فرمائید.
        /// </summary>
        internal static string Code23 {
            get {
                return ResourceManager.GetString("Code23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Merchant. پذيرنده کارت فعال نیست لطفا با بخش امور پذيرندگان، تماس حاصل فرمائید.
        /// </summary>
        internal static string Code3 {
            get {
                return ResourceManager.GetString("Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام تراکنش مربوطه توسط پايانه ی انجام دهنده مجاز نمی باشد..
        /// </summary>
        internal static string Code58 {
            get {
                return ResourceManager.GetString("Code58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش از حد مجاز بالاتر است.
        /// </summary>
        internal static string Code61 {
            get {
                return ResourceManager.GetString("Code61", resourceCulture);
            }
        }
    }
}
